import type { CameraLutCubeSize, CameraLutExportOptions, CameraLutExportResult } from "../types";
import { composeCubeSamples } from "./cubeCompose";
import { formatEvForHeader, formatShootingTargetEv, generateLutFileName, sanitizeLutName } from "./lutNaming";

const clamp01 = (value: number): number => {
  return Math.min(Math.max(value, 0), 1);
};

const formatCubeValue = (value: number): string => {
  return clamp01(value).toFixed(6);
};

const sanitizeHeaderValue = (value: string): string => {
  return value.replace(/[\r\n"]/g, " ").trim();
};

const resolveCubeSize = (options: CameraLutExportOptions): CameraLutCubeSize => {
  const requestedSize = options.requestedCubeSize === "auto" ? options.profile.recommendedCubeSize ?? 33 : options.requestedCubeSize;
  const maxSize = options.profile.maxCubeSize;

  if (maxSize === "unknown" || maxSize === undefined) {
    return requestedSize;
  }

  if (requestedSize > maxSize) {
    throw new Error(`当前机型目录限制最高 ${maxSize} 点 LUT，不能导出 ${requestedSize} 点相机监看 LUT。`);
  }

  return requestedSize;
};

export const generateCameraMonitoringCubeLut = (options: CameraLutExportOptions): CameraLutExportResult => {
  const lutSize = resolveCubeSize(options);
  const finalLutName = sanitizeLutName(options.lutName);
  const title = finalLutName.length > 0 ? finalLutName : "AI_Film_Camera_Monitoring_LUT";
  const fileName = generateLutFileName(title);
  const dataStatus = options.profile.dataStatus;
  const technicalTransform = options.technicalTransform;
  const verificationStatus =
    dataStatus === "verified-official" && technicalTransform?.verification === "verified-official" ? "verified" : "TEST";
  const technicalSource = technicalTransform?.sourceTitle ?? "none";
  const technicalSourceId = technicalTransform?.sourceId ?? "none";
  const technicalFileName = technicalTransform?.fileName ?? "none";
  const technicalVerification = technicalTransform?.verification ?? "none";
  const outputSpace = technicalTransform?.outputSpace ?? "Camera monitoring output / experimental";
  const lines: string[] = [
    `TITLE "${title}"`,
    "# Generated by AI Film LUT Studio",
    "# LUT Export Type: Camera Monitoring LUT",
    "# Export Type Code: CAMMON",
    `# Verification Status: ${verificationStatus} / ${dataStatus}`,
    `# Technical Conversion Status: ${technicalTransform === undefined ? "not-bound" : "active"}`,
    `# Technical Transform Source: ${sanitizeHeaderValue(technicalSource)}`,
    `# Technical Transform File Name: ${sanitizeHeaderValue(technicalFileName)}`,
    `# Technical Transform Source ID: ${sanitizeHeaderValue(technicalSourceId)}`,
    `# Technical Transform Verification: ${technicalVerification}`,
    `# Camera Brand: ${sanitizeHeaderValue(options.profile.brandLabel)}`,
    `# Camera Model: ${sanitizeHeaderValue(options.profile.modelName)}`,
    `# Firmware Scope: ${sanitizeHeaderValue(options.profile.firmwareScope?.join(" / ") ?? "unknown")}`,
    `# Sensor Format: ${options.profile.sensorFormat ?? "unknown"}`,
    `# Input Gamma: ${sanitizeHeaderValue(options.selectedLogProfile)}`,
    `# Input Gamut: ${sanitizeHeaderValue(options.selectedGamut)}`,
    `# Output Space: ${sanitizeHeaderValue(outputSpace)}`,
    `# Creative Look: ${sanitizeHeaderValue(title)}`,
    `# LUT Use Type: ${options.lutUseType}`,
    `# LUT Size: ${lutSize}`,
    `# Range: ${options.range}`,
    `# Monitoring Mode: ${options.exposureConfig.mode}`,
    `# Shooting Target EV: ${formatShootingTargetEv(options.exposureConfig)}`,
    `# LUT Brightness Offset: ${formatEvForHeader(options.exposureConfig.lutBrightnessOffsetEv)}`,
    `# User Selected Monitor Offset: ${formatEvForHeader(options.exposureConfig.lutBrightnessOffsetEv)}`,
    "# Community Advice Included: false",
    `# Data Status: ${dataStatus}`,
    "# Warning: Verify compatibility with your camera before production use.",
    "# Note: This LUT is not an official technical conversion LUT unless verified.",
    "# Note: LUT brightness offset changes only monitoring display brightness and does not change actual camera exposure.",
    dataStatus === "verified-official"
      ? "# Compatibility: Official profile data has been marked as verified."
      : "# Compatibility: This camera profile still needs official confirmation. Test before production use.",
    `LUT_3D_SIZE ${lutSize}`,
    "DOMAIN_MIN 0.0 0.0 0.0",
    "DOMAIN_MAX 1.0 1.0 1.0"
  ];
  const samples = composeCubeSamples(lutSize, {
    ...(technicalTransform === undefined ? {} : { inputTechnicalTransform: technicalTransform }),
    creativeLookTransform: {
      adjustments: options.adjustments,
      ...(options.referenceAverageColor === undefined ? {} : { referenceAverageColor: options.referenceAverageColor })
    },
    monitorAdjustment: { brightnessOffsetEv: options.exposureConfig.lutBrightnessOffsetEv },
    rangeMapping: options.range
  });
  samples.forEach((output) => lines.push(`${formatCubeValue(output.r)} ${formatCubeValue(output.g)} ${formatCubeValue(output.b)}`));

  return {
    fileName,
    content: `${lines.join("\n")}\n`,
    lutSize,
    dataLineCount: lutSize * lutSize * lutSize,
    exportType: "camera-monitoring",
    exportKind: "camera-monitoring",
    exportTypeCode: "CAMMON",
    verificationStatus,
    lookName: title,
    outputColorSpace: outputSpace,
    sourceHintBrand: options.profile.brandLabel,
    sourceHintGamma: options.selectedLogProfile,
    cameraBrand: options.profile.brandLabel,
    cameraModel: options.profile.modelName,
    gamma: options.selectedLogProfile,
    gamut: options.selectedGamut,
    range: options.range,
    exposureConfig: options.exposureConfig,
    dataStatus,
    ...(technicalTransform === undefined
      ? { technicalTransformVerification: "none" as const }
      : {
          technicalTransformFileName: technicalTransform.fileName,
          ...(technicalTransform.sourceId === undefined ? {} : { technicalTransformSourceId: technicalTransform.sourceId }),
          ...(technicalTransform.sourceTitle === undefined ? {} : { technicalTransformSourceTitle: technicalTransform.sourceTitle }),
          technicalTransformVerification: technicalTransform.verification
        })
  };
};

export const downloadCameraMonitoringLut = (result: CameraLutExportResult): void => {
  const blob = new Blob([result.content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = result.fileName;
  anchor.rel = "noopener";
  anchor.style.display = "none";
  document.body.appendChild(anchor);
  anchor.click();

  window.setTimeout(() => {
    anchor.remove();
    URL.revokeObjectURL(url);
  }, 1000);
};
