import type { CameraLutCubeSize, CameraLutExportOptions, CameraLutExportResult, CameraLutRange, RgbColor } from "../types";
import { applyLookToRgb } from "./cubeExport";
import { formatEvForHeader, formatShootingTargetEv, sanitizeLutFileName, sanitizeLutName } from "./lutNaming";

const clamp01 = (value: number): number => {
  return Math.min(Math.max(value, 0), 1);
};

const formatCubeValue = (value: number): string => {
  return clamp01(value).toFixed(6);
};

const sanitizeHeaderValue = (value: string): string => {
  return value.replace(/[\r\n"]/g, " ").trim();
};

const resolveCubeSize = (options: CameraLutExportOptions): CameraLutCubeSize => {
  const requestedSize = options.requestedCubeSize === "auto" ? options.profile.recommendedCubeSize ?? 33 : options.requestedCubeSize;
  const maxSize = options.profile.maxCubeSize;

  if (maxSize === "unknown" || maxSize === undefined) {
    return requestedSize;
  }

  if (requestedSize > maxSize) {
    throw new Error(`当前机型目录限制最高 ${maxSize} 点 LUT，不能导出 ${requestedSize} 点相机监看 LUT。`);
  }

  return requestedSize;
};

const applyMonitoringBrightnessOffset = (color: RgbColor, brightnessOffsetEv: number): RgbColor => {
  const factor = 2 ** brightnessOffsetEv;

  if (factor === 1) {
    return color;
  }

  const mapChannel = (value: number): number => {
    const boosted = clamp01(value) * factor;

    if (boosted <= 0.9) {
      return clamp01(boosted);
    }

    return clamp01(0.9 + (1 - Math.exp(-(boosted - 0.9) * 2.4)) * 0.1);
  };

  return {
    r: mapChannel(color.r),
    g: mapChannel(color.g),
    b: mapChannel(color.b)
  };
};

const applyOutputRange = (color: RgbColor, range: CameraLutRange): RgbColor => {
  if (range !== "legal") {
    return color;
  }

  const legalMin = 16 / 255;
  const legalScale = 219 / 255;

  return {
    r: legalMin + clamp01(color.r) * legalScale,
    g: legalMin + clamp01(color.g) * legalScale,
    b: legalMin + clamp01(color.b) * legalScale
  };
};

export const generateCameraMonitoringCubeLut = (options: CameraLutExportOptions): CameraLutExportResult => {
  const lutSize = resolveCubeSize(options);
  const maxIndex = lutSize - 1;
  const finalLutName = sanitizeLutName(options.lutName);
  const title = finalLutName.length > 0 ? finalLutName : "AI_Film_Camera_Monitoring_LUT";
  const fileName = sanitizeLutFileName(title);
  const dataStatus = options.profile.dataStatus;
  const lines: string[] = [
    `TITLE "${title}"`,
    "# Generated by AI Film LUT Studio",
    "# LUT Export Type: Camera Monitoring LUT",
    `# Camera Brand: ${sanitizeHeaderValue(options.profile.brandLabel)}`,
    `# Camera Model: ${sanitizeHeaderValue(options.profile.modelName)}`,
    `# Sensor Format: ${options.profile.sensorFormat ?? "unknown"}`,
    `# Input Gamma: ${sanitizeHeaderValue(options.selectedLogProfile)}`,
    `# Input Gamut: ${sanitizeHeaderValue(options.selectedGamut)}`,
    `# LUT Use Type: ${options.lutUseType}`,
    `# LUT Size: ${lutSize}`,
    `# Range: ${options.range}`,
    `# Monitoring Mode: ${options.exposureConfig.mode}`,
    `# Shooting Target EV: ${formatShootingTargetEv(options.exposureConfig)}`,
    `# LUT Brightness Offset: ${formatEvForHeader(options.exposureConfig.lutBrightnessOffsetEv)}`,
    `# Data Status: ${dataStatus}`,
    "# Warning: Verify compatibility with your camera before production use.",
    "# Note: This LUT is not an official technical conversion LUT unless verified.",
    "# Note: LUT brightness offset changes only monitoring display brightness and does not change actual camera exposure.",
    dataStatus === "verified-official"
      ? "# Compatibility: Official profile data has been marked as verified."
      : "# Compatibility: This camera profile still needs official confirmation. Test before production use.",
    `LUT_3D_SIZE ${lutSize}`,
    "DOMAIN_MIN 0.0 0.0 0.0",
    "DOMAIN_MAX 1.0 1.0 1.0"
  ];

  for (let blueIndex = 0; blueIndex < lutSize; blueIndex += 1) {
    const b = blueIndex / maxIndex;

    for (let greenIndex = 0; greenIndex < lutSize; greenIndex += 1) {
      const g = greenIndex / maxIndex;

      for (let redIndex = 0; redIndex < lutSize; redIndex += 1) {
        const r = redIndex / maxIndex;
        const creativeColor = applyLookToRgb({ r, g, b }, options.adjustments, options.referenceAverageColor);
        const exposureColor = applyMonitoringBrightnessOffset(creativeColor, options.exposureConfig.lutBrightnessOffsetEv);
        const output = applyOutputRange(exposureColor, options.range);
        lines.push(`${formatCubeValue(output.r)} ${formatCubeValue(output.g)} ${formatCubeValue(output.b)}`);
      }
    }
  }

  return {
    fileName,
    content: `${lines.join("\n")}\n`,
    lutSize,
    dataLineCount: lutSize * lutSize * lutSize,
    exportType: "camera-monitoring",
    cameraBrand: options.profile.brandLabel,
    cameraModel: options.profile.modelName,
    gamma: options.selectedLogProfile,
    gamut: options.selectedGamut,
    range: options.range,
    exposureConfig: options.exposureConfig,
    dataStatus
  };
};

export const downloadCameraMonitoringLut = (result: CameraLutExportResult): void => {
  const blob = new Blob([result.content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = result.fileName;
  anchor.rel = "noopener";
  anchor.style.display = "none";
  document.body.appendChild(anchor);
  anchor.click();

  window.setTimeout(() => {
    anchor.remove();
    URL.revokeObjectURL(url);
  }, 1000);
};
