import type { ColorPreviewAdjustments, CubeExportResult, LutExportOptions, RgbColor } from "../types";

const clamp01 = (value: number): number => {
  return Math.min(Math.max(value, 0), 1);
};

const formatCubeValue = (value: number): string => {
  return clamp01(value).toFixed(6);
};

const sanitizeLutTitle = (lutName: string): string => {
  return lutName.replace(/["\r\n]/g, " ").trim() || "AI Film LUT Studio";
};

const sanitizeFileName = (lutName: string): string => {
  const cleaned = lutName
    .trim()
    .replace(/[\\/:*?"<>|]/g, "-")
    .replace(/\s+/g, "_");

  return `${cleaned.length > 0 ? cleaned : "AI_Film_LUT_Studio"}.cube`;
};

const normalizeLutSize = (lutSize: number): number => {
  if (lutSize === 17 || lutSize === 33 || lutSize === 65) {
    return lutSize;
  }

  return 33;
};

export const applyLookToRgb = (input: RgbColor, adjustments: ColorPreviewAdjustments, referenceAverageColor?: RgbColor): RgbColor => {
  const originalR = clamp01(input.r);
  const originalG = clamp01(input.g);
  const originalB = clamp01(input.b);
  const originalLuma = 0.299 * originalR + 0.587 * originalG + 0.114 * originalB;
  const intensity = clamp01(adjustments.intensity / 100);
  const contrastValue = Math.min(Math.max(adjustments.contrast, -100), 100) * 1.8;
  const contrastFactor = (259 * (contrastValue + 255)) / (255 * (259 - contrastValue));
  const saturationFactor = 1 + Math.min(Math.max(adjustments.saturation, -100), 100) / 100;
  const temperatureShift = Math.min(Math.max(adjustments.temperature, -50), 50) * 1.15 / 255;
  const tintShift = Math.min(Math.max(adjustments.tint, -50), 50) * 0.9 / 255;
  const shadowShift = clamp01(adjustments.shadowMatch / 100);
  const midtoneShift = clamp01(adjustments.midtoneMatch / 100);
  const highlightShift = clamp01(adjustments.highlightMatch / 100);
  const referenceStrength = referenceAverageColor === undefined ? 0 : Math.min(0.24, 0.08 + intensity * 0.16);
  const saturationCeiling = adjustments.preventOversaturation ? 246 / 255 : 1;
  const lumaPreserveStrength = adjustments.preserveLuma ? 0.52 : 0.18;
  let r = originalR;
  let g = originalG;
  let b = originalB;

  r = contrastFactor * (r - 0.5) + 0.5;
  g = contrastFactor * (g - 0.5) + 0.5;
  b = contrastFactor * (b - 0.5) + 0.5;

  const gray = 0.299 * r + 0.587 * g + 0.114 * b;
  r = gray + (r - gray) * saturationFactor;
  g = gray + (g - gray) * saturationFactor;
  b = gray + (b - gray) * saturationFactor;

  r += temperatureShift;
  b -= temperatureShift;

  r += tintShift * 0.55;
  b += tintShift * 0.55;
  g -= tintShift;

  if (originalLuma < 0.33) {
    r += (shadowShift - 0.5) * 15 / 255;
    b += (0.5 - shadowShift) * 9 / 255;
    g += (shadowShift - 0.5) * 4 / 255;
  } else if (originalLuma < 0.66) {
    r += (midtoneShift - 0.5) * 13 / 255;
    g += (midtoneShift - 0.5) * 7 / 255;
    b -= (midtoneShift - 0.5) * 5 / 255;
  } else {
    r += (highlightShift - 0.5) * 9 / 255;
    g += (highlightShift - 0.5) * 5 / 255;
    b -= (highlightShift - 0.5) * 7 / 255;
  }

  if (referenceAverageColor !== undefined) {
    r += (clamp01(referenceAverageColor.r) - 0.5) * referenceStrength;
    g += (clamp01(referenceAverageColor.g) - 0.5) * referenceStrength;
    b += (clamp01(referenceAverageColor.b) - 0.5) * referenceStrength;
  }

  if (adjustments.skinToneProtection) {
    const maxChannel = Math.max(originalR, originalG, originalB);
    const minChannel = Math.min(originalR, originalG, originalB);
    const isWarmMidtone =
      originalR > originalB && originalR > originalG * 0.9 && originalG > originalB * 0.72 && maxChannel - minChannel > 18 / 255;

    if (isWarmMidtone && originalLuma > 0.22 && originalLuma < 0.82) {
      r = originalR * 0.34 + r * 0.66;
      g = originalG * 0.28 + g * 0.72;
      b = originalB * 0.34 + b * 0.66;
    }
  }

  if (adjustments.preserveLuma) {
    const adjustedLuma = 0.299 * r + 0.587 * g + 0.114 * b;
    const lumaDelta = originalLuma - adjustedLuma;
    r += lumaDelta * lumaPreserveStrength;
    g += lumaDelta * lumaPreserveStrength;
    b += lumaDelta * lumaPreserveStrength;
  }

  return {
    r: clamp01(Math.min(originalR * (1 - intensity) + r * intensity, saturationCeiling)),
    g: clamp01(Math.min(originalG * (1 - intensity) + g * intensity, saturationCeiling)),
    b: clamp01(Math.min(originalB * (1 - intensity) + b * intensity, saturationCeiling))
  };
};

export const generateCubeLut = ({ lutName, lutSize, adjustments, referenceAverageColor }: LutExportOptions): CubeExportResult => {
  const normalizedSize = normalizeLutSize(lutSize);
  const maxIndex = normalizedSize - 1;
  const lines: string[] = [
    `TITLE "${sanitizeLutTitle(lutName)}"`,
    "# Generated by AI Film LUT Studio",
    "# Basic creative Rec.709/display-space LUT. Not a camera Log technical conversion LUT.",
    `LUT_3D_SIZE ${normalizedSize}`,
    "DOMAIN_MIN 0.0 0.0 0.0",
    "DOMAIN_MAX 1.0 1.0 1.0"
  ];

  for (let blueIndex = 0; blueIndex < normalizedSize; blueIndex += 1) {
    const b = blueIndex / maxIndex;

    for (let greenIndex = 0; greenIndex < normalizedSize; greenIndex += 1) {
      const g = greenIndex / maxIndex;

      for (let redIndex = 0; redIndex < normalizedSize; redIndex += 1) {
        const r = redIndex / maxIndex;
        const output = applyLookToRgb({ r, g, b }, adjustments, referenceAverageColor);
        lines.push(`${formatCubeValue(output.r)} ${formatCubeValue(output.g)} ${formatCubeValue(output.b)}`);
      }
    }
  }

  return {
    fileName: sanitizeFileName(lutName),
    content: `${lines.join("\n")}\n`,
    lutSize: normalizedSize,
    dataLineCount: normalizedSize * normalizedSize * normalizedSize
  };
};

export const downloadCubeLut = (result: CubeExportResult): void => {
  const blob = new Blob([result.content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  try {
    anchor.href = url;
    anchor.download = result.fileName;
    anchor.rel = "noopener";
    document.body.appendChild(anchor);
    anchor.click();
  } finally {
    anchor.remove();
    URL.revokeObjectURL(url);
  }
};
